/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRoomCheckRouteImport } from './routes/_authenticated/room-check'
import { Route as AuthenticatedReconciliationRouteImport } from './routes/_authenticated/reconciliation'
import { Route as AuthenticatedQrScannerRouteImport } from './routes/_authenticated/qr-scanner'
import { Route as AuthenticatedPantryRouteImport } from './routes/_authenticated/pantry'
import { Route as AuthenticatedMovementRouteImport } from './routes/_authenticated/movement'
import { Route as AuthenticatedMasterRouteImport } from './routes/_authenticated/master'
import { Route as AuthenticatedLostRouteImport } from './routes/_authenticated/lost'
import { Route as AuthenticatedLaundryRouteImport } from './routes/_authenticated/laundry'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBreakageRouteImport } from './routes/_authenticated/breakage'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoomCheckRoute = AuthenticatedRoomCheckRouteImport.update({
  id: '/room-check',
  path: '/room-check',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReconciliationRoute =
  AuthenticatedReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQrScannerRoute = AuthenticatedQrScannerRouteImport.update({
  id: '/qr-scanner',
  path: '/qr-scanner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPantryRoute = AuthenticatedPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMovementRoute = AuthenticatedMovementRouteImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMasterRoute = AuthenticatedMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLostRoute = AuthenticatedLostRouteImport.update({
  id: '/lost',
  path: '/lost',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLaundryRoute = AuthenticatedLaundryRouteImport.update({
  id: '/laundry',
  path: '/laundry',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBreakageRoute = AuthenticatedBreakageRouteImport.update({
  id: '/breakage',
  path: '/breakage',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/breakage': typeof AuthenticatedBreakageRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/laundry': typeof AuthenticatedLaundryRoute
  '/lost': typeof AuthenticatedLostRoute
  '/master': typeof AuthenticatedMasterRoute
  '/movement': typeof AuthenticatedMovementRoute
  '/pantry': typeof AuthenticatedPantryRoute
  '/qr-scanner': typeof AuthenticatedQrScannerRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/room-check': typeof AuthenticatedRoomCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/breakage': typeof AuthenticatedBreakageRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/laundry': typeof AuthenticatedLaundryRoute
  '/lost': typeof AuthenticatedLostRoute
  '/master': typeof AuthenticatedMasterRoute
  '/movement': typeof AuthenticatedMovementRoute
  '/pantry': typeof AuthenticatedPantryRoute
  '/qr-scanner': typeof AuthenticatedQrScannerRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/room-check': typeof AuthenticatedRoomCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/breakage': typeof AuthenticatedBreakageRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/laundry': typeof AuthenticatedLaundryRoute
  '/_authenticated/lost': typeof AuthenticatedLostRoute
  '/_authenticated/master': typeof AuthenticatedMasterRoute
  '/_authenticated/movement': typeof AuthenticatedMovementRoute
  '/_authenticated/pantry': typeof AuthenticatedPantryRoute
  '/_authenticated/qr-scanner': typeof AuthenticatedQrScannerRoute
  '/_authenticated/reconciliation': typeof AuthenticatedReconciliationRoute
  '/_authenticated/room-check': typeof AuthenticatedRoomCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/breakage'
    | '/dashboard'
    | '/inventory'
    | '/laundry'
    | '/lost'
    | '/master'
    | '/movement'
    | '/pantry'
    | '/qr-scanner'
    | '/reconciliation'
    | '/room-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/breakage'
    | '/dashboard'
    | '/inventory'
    | '/laundry'
    | '/lost'
    | '/master'
    | '/movement'
    | '/pantry'
    | '/qr-scanner'
    | '/reconciliation'
    | '/room-check'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/breakage'
    | '/_authenticated/dashboard'
    | '/_authenticated/inventory'
    | '/_authenticated/laundry'
    | '/_authenticated/lost'
    | '/_authenticated/master'
    | '/_authenticated/movement'
    | '/_authenticated/pantry'
    | '/_authenticated/qr-scanner'
    | '/_authenticated/reconciliation'
    | '/_authenticated/room-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/room-check': {
      id: '/_authenticated/room-check'
      path: '/room-check'
      fullPath: '/room-check'
      preLoaderRoute: typeof AuthenticatedRoomCheckRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reconciliation': {
      id: '/_authenticated/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof AuthenticatedReconciliationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qr-scanner': {
      id: '/_authenticated/qr-scanner'
      path: '/qr-scanner'
      fullPath: '/qr-scanner'
      preLoaderRoute: typeof AuthenticatedQrScannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pantry': {
      id: '/_authenticated/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AuthenticatedPantryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/movement': {
      id: '/_authenticated/movement'
      path: '/movement'
      fullPath: '/movement'
      preLoaderRoute: typeof AuthenticatedMovementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master': {
      id: '/_authenticated/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedMasterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lost': {
      id: '/_authenticated/lost'
      path: '/lost'
      fullPath: '/lost'
      preLoaderRoute: typeof AuthenticatedLostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/laundry': {
      id: '/_authenticated/laundry'
      path: '/laundry'
      fullPath: '/laundry'
      preLoaderRoute: typeof AuthenticatedLaundryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/breakage': {
      id: '/_authenticated/breakage'
      path: '/breakage'
      fullPath: '/breakage'
      preLoaderRoute: typeof AuthenticatedBreakageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBreakageRoute: typeof AuthenticatedBreakageRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLaundryRoute: typeof AuthenticatedLaundryRoute
  AuthenticatedLostRoute: typeof AuthenticatedLostRoute
  AuthenticatedMasterRoute: typeof AuthenticatedMasterRoute
  AuthenticatedMovementRoute: typeof AuthenticatedMovementRoute
  AuthenticatedPantryRoute: typeof AuthenticatedPantryRoute
  AuthenticatedQrScannerRoute: typeof AuthenticatedQrScannerRoute
  AuthenticatedReconciliationRoute: typeof AuthenticatedReconciliationRoute
  AuthenticatedRoomCheckRoute: typeof AuthenticatedRoomCheckRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBreakageRoute: AuthenticatedBreakageRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLaundryRoute: AuthenticatedLaundryRoute,
  AuthenticatedLostRoute: AuthenticatedLostRoute,
  AuthenticatedMasterRoute: AuthenticatedMasterRoute,
  AuthenticatedMovementRoute: AuthenticatedMovementRoute,
  AuthenticatedPantryRoute: AuthenticatedPantryRoute,
  AuthenticatedQrScannerRoute: AuthenticatedQrScannerRoute,
  AuthenticatedReconciliationRoute: AuthenticatedReconciliationRoute,
  AuthenticatedRoomCheckRoute: AuthenticatedRoomCheckRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
